import type { Metadata } from "next";
import { PageFrame } from "@/components/PageFrame";

export const metadata: Metadata = { title: "HumMod", description: "Learn how UTSC CPG uses and extends HumMod, and request the latest UTSC-CPG release." };

export default function HumModPage() {
  return <PageFrame>
    <section className="page-hero hummod-hero content-width"><div><p className="eyebrow">What is HumMod?</p><h1>A whole body, expressed as relationships.</h1><p className="page-deck">HumMod is a large integrative mathematical model that lets researchers change conditions, run time forward, and observe interacting physiological responses.</p></div><div className="metric-stack"><div><strong>11K+</strong><span>interacting variables</span></div><div><strong>Whole-body</strong><span>time-dependent simulation</span></div><div><strong>Windows</strong><span>current supported platform</span></div></div></section>
    <section className="split-section content-width"><div><p className="section-number">01</p><h2>Why use a model?</h2></div><div className="prose"><p>A whole-body model makes feedback visible. A change in absorption can alter metabolism; altered metabolism can affect circulation, kidney function, or neural state. HumMod provides a common environment for tracing those relationships.</p><p>At UTSC, the model is both an experimental system and a teaching platform. Students learn to turn a physiological hypothesis into equations, model structure, simulations, validation, and scientific arguments.</p></div></section>
    <section className="feature-band"><div className="content-width"><p className="eyebrow">UTSC-CPG direction</p><h2>Extending who and what the virtual patient can represent.</h2><div className="feature-grid"><article><h3>New physiology</h3><p>Pregnancy, ethanol pharmacokinetics, sleep, nutrition, exercise, dopamine, and more.</p></article><article><h3>Population variation</h3><p>Sex, age, renal variation, skin pigmentation, and other contexts historically underrepresented in model inputs.</p></article><article><h3>Research training</h3><p>A structured route from course-based simulation to independent undergraduate scholarship.</p></article></div></div></section>
    <section className="download-card content-width" id="download"><div><p className="eyebrow">Request access</p><h2>UTSC-CPG HumMod v1.9</h2><p>The current release is designed for Windows. The request form collects enough information for the group to follow up with access and installation guidance; submission does not start an automatic download.</p><p className="small-note">Version number, distribution terms, and support statement require final faculty review before launch.</p></div><div className="download-actions"><a className="button button-primary" href="https://forms.gle/F4FLtTzbN2eJgxR17" target="_blank" rel="noreferrer">Open the request form ↗</a><a className="text-link" href="https://hummod.org/origin-story/" target="_blank" rel="noreferrer">Read the HumMod origin story ↗</a></div></section>
    <section className="content-width license-note"><h2>Licensing</h2><p>HumMod is exclusively licensed to HC Simulation, LLC. UTSC-CPG distribution and support information should be read together with the terms provided through the request process.</p></section>
  </PageFrame>;
}
